# Generated by Django 6.0.3 on 2026-04-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_discount_percent_product_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, help_text='Add benefits separated by commas'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_label',
            field=models.CharField(blank=True, help_text='Example: 100 ml, 100 gm', max_length=50),
        ),
    ]
